/*
  # Add Donor Number

  1. Changes
    - Add `donor_number` column to `profiles` table
      - Bigint type
      - Auto-incrementing starting at 10001
      - Unique constraint
    - Add index for faster lookups based on donor number

  2. Notes
    - Using `GENERATED BY DEFAULT AS IDENTITY` allows manual overrides if ever needed, but handles auto-increment normally.
    - Starting at 10001 gives a nice 5-digit number to start.
*/

ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS donor_number BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10001);

-- Add unique constraint to ensure no duplicates
ALTER TABLE public.profiles 
ADD CONSTRAINT profiles_donor_number_key UNIQUE (donor_number);

-- Create index for performance
CREATE INDEX IF NOT EXISTS idx_profiles_donor_number ON public.profiles(donor_number);
